    vkCreateInstance: TvkCreateInstance{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkDestroyInstance: TvkDestroyInstance{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkEnumeratePhysicalDevices: TvkEnumeratePhysicalDevices{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetDeviceProcAddr: TvkGetDeviceProcAddr{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetInstanceProcAddr: TvkGetInstanceProcAddr{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetPhysicalDeviceProperties: TvkGetPhysicalDeviceProperties{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetPhysicalDeviceQueueFamilyProperties: TvkGetPhysicalDeviceQueueFamilyProperties{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetPhysicalDeviceMemoryProperties: TvkGetPhysicalDeviceMemoryProperties{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetPhysicalDeviceFeatures: TvkGetPhysicalDeviceFeatures{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetPhysicalDeviceFormatProperties: TvkGetPhysicalDeviceFormatProperties{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetPhysicalDeviceImageFormatProperties: TvkGetPhysicalDeviceImageFormatProperties{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCreateDevice: TvkCreateDevice{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkDestroyDevice: TvkDestroyDevice{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkEnumerateInstanceLayerProperties: TvkEnumerateInstanceLayerProperties{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkEnumerateInstanceExtensionProperties: TvkEnumerateInstanceExtensionProperties{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkEnumerateDeviceLayerProperties: TvkEnumerateDeviceLayerProperties{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkEnumerateDeviceExtensionProperties: TvkEnumerateDeviceExtensionProperties{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetDeviceQueue: TvkGetDeviceQueue{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkQueueSubmit: TvkQueueSubmit{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkQueueWaitIdle: TvkQueueWaitIdle{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkDeviceWaitIdle: TvkDeviceWaitIdle{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkAllocateMemory: TvkAllocateMemory{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkFreeMemory: TvkFreeMemory{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkMapMemory: TvkMapMemory{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkUnmapMemory: TvkUnmapMemory{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkFlushMappedMemoryRanges: TvkFlushMappedMemoryRanges{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkInvalidateMappedMemoryRanges: TvkInvalidateMappedMemoryRanges{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetDeviceMemoryCommitment: TvkGetDeviceMemoryCommitment{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetBufferMemoryRequirements: TvkGetBufferMemoryRequirements{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkBindBufferMemory: TvkBindBufferMemory{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetImageMemoryRequirements: TvkGetImageMemoryRequirements{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkBindImageMemory: TvkBindImageMemory{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetImageSparseMemoryRequirements: TvkGetImageSparseMemoryRequirements{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetPhysicalDeviceSparseImageFormatProperties: TvkGetPhysicalDeviceSparseImageFormatProperties{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkQueueBindSparse: TvkQueueBindSparse{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCreateFence: TvkCreateFence{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkDestroyFence: TvkDestroyFence{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkResetFences: TvkResetFences{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetFenceStatus: TvkGetFenceStatus{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkWaitForFences: TvkWaitForFences{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCreateSemaphore: TvkCreateSemaphore{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkDestroySemaphore: TvkDestroySemaphore{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCreateEvent: TvkCreateEvent{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkDestroyEvent: TvkDestroyEvent{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetEventStatus: TvkGetEventStatus{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkSetEvent: TvkSetEvent{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkResetEvent: TvkResetEvent{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCreateQueryPool: TvkCreateQueryPool{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkDestroyQueryPool: TvkDestroyQueryPool{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetQueryPoolResults: TvkGetQueryPoolResults{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCreateBuffer: TvkCreateBuffer{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkDestroyBuffer: TvkDestroyBuffer{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCreateBufferView: TvkCreateBufferView{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkDestroyBufferView: TvkDestroyBufferView{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCreateImage: TvkCreateImage{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkDestroyImage: TvkDestroyImage{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetImageSubresourceLayout: TvkGetImageSubresourceLayout{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCreateImageView: TvkCreateImageView{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkDestroyImageView: TvkDestroyImageView{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCreateShaderModule: TvkCreateShaderModule{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkDestroyShaderModule: TvkDestroyShaderModule{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCreatePipelineCache: TvkCreatePipelineCache{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkDestroyPipelineCache: TvkDestroyPipelineCache{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetPipelineCacheData: TvkGetPipelineCacheData{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkMergePipelineCaches: TvkMergePipelineCaches{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCreateGraphicsPipelines: TvkCreateGraphicsPipelines{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCreateComputePipelines: TvkCreateComputePipelines{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkDestroyPipeline: TvkDestroyPipeline{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCreatePipelineLayout: TvkCreatePipelineLayout{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkDestroyPipelineLayout: TvkDestroyPipelineLayout{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCreateSampler: TvkCreateSampler{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkDestroySampler: TvkDestroySampler{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCreateDescriptorSetLayout: TvkCreateDescriptorSetLayout{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkDestroyDescriptorSetLayout: TvkDestroyDescriptorSetLayout{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCreateDescriptorPool: TvkCreateDescriptorPool{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkDestroyDescriptorPool: TvkDestroyDescriptorPool{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkResetDescriptorPool: TvkResetDescriptorPool{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkAllocateDescriptorSets: TvkAllocateDescriptorSets{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkFreeDescriptorSets: TvkFreeDescriptorSets{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkUpdateDescriptorSets: TvkUpdateDescriptorSets{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCreateFramebuffer: TvkCreateFramebuffer{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkDestroyFramebuffer: TvkDestroyFramebuffer{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCreateRenderPass: TvkCreateRenderPass{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkDestroyRenderPass: TvkDestroyRenderPass{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetRenderAreaGranularity: TvkGetRenderAreaGranularity{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCreateCommandPool: TvkCreateCommandPool{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkDestroyCommandPool: TvkDestroyCommandPool{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkResetCommandPool: TvkResetCommandPool{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkAllocateCommandBuffers: TvkAllocateCommandBuffers{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkFreeCommandBuffers: TvkFreeCommandBuffers{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkBeginCommandBuffer: TvkBeginCommandBuffer{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkEndCommandBuffer: TvkEndCommandBuffer{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkResetCommandBuffer: TvkResetCommandBuffer{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdBindPipeline: TvkCmdBindPipeline{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdSetViewport: TvkCmdSetViewport{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdSetScissor: TvkCmdSetScissor{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdSetLineWidth: TvkCmdSetLineWidth{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdSetDepthBias: TvkCmdSetDepthBias{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdSetBlendConstants: TvkCmdSetBlendConstants{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdSetDepthBounds: TvkCmdSetDepthBounds{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdSetStencilCompareMask: TvkCmdSetStencilCompareMask{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdSetStencilWriteMask: TvkCmdSetStencilWriteMask{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdSetStencilReference: TvkCmdSetStencilReference{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdBindDescriptorSets: TvkCmdBindDescriptorSets{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdBindIndexBuffer: TvkCmdBindIndexBuffer{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdBindVertexBuffers: TvkCmdBindVertexBuffers{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdDraw: TvkCmdDraw{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdDrawIndexed: TvkCmdDrawIndexed{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdDrawIndirect: TvkCmdDrawIndirect{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdDrawIndexedIndirect: TvkCmdDrawIndexedIndirect{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdDispatch: TvkCmdDispatch{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdDispatchIndirect: TvkCmdDispatchIndirect{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdCopyBuffer: TvkCmdCopyBuffer{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdCopyImage: TvkCmdCopyImage{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdBlitImage: TvkCmdBlitImage{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdCopyBufferToImage: TvkCmdCopyBufferToImage{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdCopyImageToBuffer: TvkCmdCopyImageToBuffer{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdUpdateBuffer: TvkCmdUpdateBuffer{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdFillBuffer: TvkCmdFillBuffer{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdClearColorImage: TvkCmdClearColorImage{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdClearDepthStencilImage: TvkCmdClearDepthStencilImage{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdClearAttachments: TvkCmdClearAttachments{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdResolveImage: TvkCmdResolveImage{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdSetEvent: TvkCmdSetEvent{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdResetEvent: TvkCmdResetEvent{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdWaitEvents: TvkCmdWaitEvents{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdPipelineBarrier: TvkCmdPipelineBarrier{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdBeginQuery: TvkCmdBeginQuery{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdEndQuery: TvkCmdEndQuery{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdResetQueryPool: TvkCmdResetQueryPool{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdWriteTimestamp: TvkCmdWriteTimestamp{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdCopyQueryPoolResults: TvkCmdCopyQueryPoolResults{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdPushConstants: TvkCmdPushConstants{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdBeginRenderPass: TvkCmdBeginRenderPass{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdNextSubpass: TvkCmdNextSubpass{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdEndRenderPass: TvkCmdEndRenderPass{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdExecuteCommands: TvkCmdExecuteCommands{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
{$IFDEF VK_USE_PLATFORM_ANDROID_KHR}
    vkCreateAndroidSurfaceKHR: TvkCreateAndroidSurfaceKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
{$ENDIF VK_USE_PLATFORM_ANDROID_KHR}
    vkGetPhysicalDeviceDisplayPropertiesKHR: TvkGetPhysicalDeviceDisplayPropertiesKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetPhysicalDeviceDisplayPlanePropertiesKHR: TvkGetPhysicalDeviceDisplayPlanePropertiesKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetDisplayPlaneSupportedDisplaysKHR: TvkGetDisplayPlaneSupportedDisplaysKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetDisplayModePropertiesKHR: TvkGetDisplayModePropertiesKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCreateDisplayModeKHR: TvkCreateDisplayModeKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetDisplayPlaneCapabilitiesKHR: TvkGetDisplayPlaneCapabilitiesKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCreateDisplayPlaneSurfaceKHR: TvkCreateDisplayPlaneSurfaceKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCreateSharedSwapchainsKHR: TvkCreateSharedSwapchainsKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
{$IFDEF VK_USE_PLATFORM_MIR_KHR}
    vkCreateMirSurfaceKHR: TvkCreateMirSurfaceKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
{$ENDIF VK_USE_PLATFORM_MIR_KHR}
{$IFDEF VK_USE_PLATFORM_MIR_KHR}
    vkGetPhysicalDeviceMirPresentationSupportKHR: TvkGetPhysicalDeviceMirPresentationSupportKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
{$ENDIF VK_USE_PLATFORM_MIR_KHR}
    vkDestroySurfaceKHR: TvkDestroySurfaceKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetPhysicalDeviceSurfaceSupportKHR: TvkGetPhysicalDeviceSurfaceSupportKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetPhysicalDeviceSurfaceCapabilitiesKHR: TvkGetPhysicalDeviceSurfaceCapabilitiesKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetPhysicalDeviceSurfaceFormatsKHR: TvkGetPhysicalDeviceSurfaceFormatsKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetPhysicalDeviceSurfacePresentModesKHR: TvkGetPhysicalDeviceSurfacePresentModesKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCreateSwapchainKHR: TvkCreateSwapchainKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkDestroySwapchainKHR: TvkDestroySwapchainKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetSwapchainImagesKHR: TvkGetSwapchainImagesKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkAcquireNextImageKHR: TvkAcquireNextImageKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkQueuePresentKHR: TvkQueuePresentKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
{$IFDEF VK_USE_PLATFORM_VI_NN}
    vkCreateViSurfaceNN: TvkCreateViSurfaceNN{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
{$ENDIF VK_USE_PLATFORM_VI_NN}
{$IFDEF VK_USE_PLATFORM_WAYLAND_KHR}
    vkCreateWaylandSurfaceKHR: TvkCreateWaylandSurfaceKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
{$ENDIF VK_USE_PLATFORM_WAYLAND_KHR}
{$IFDEF VK_USE_PLATFORM_WAYLAND_KHR}
    vkGetPhysicalDeviceWaylandPresentationSupportKHR: TvkGetPhysicalDeviceWaylandPresentationSupportKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
{$ENDIF VK_USE_PLATFORM_WAYLAND_KHR}
{$IFDEF VK_USE_PLATFORM_WIN32_KHR}
    vkCreateWin32SurfaceKHR: TvkCreateWin32SurfaceKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
{$ENDIF VK_USE_PLATFORM_WIN32_KHR}
{$IFDEF VK_USE_PLATFORM_WIN32_KHR}
    vkGetPhysicalDeviceWin32PresentationSupportKHR: TvkGetPhysicalDeviceWin32PresentationSupportKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
{$ENDIF VK_USE_PLATFORM_WIN32_KHR}
{$IFDEF VK_USE_PLATFORM_XLIB_KHR}
    vkCreateXlibSurfaceKHR: TvkCreateXlibSurfaceKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
{$ENDIF VK_USE_PLATFORM_XLIB_KHR}
{$IFDEF VK_USE_PLATFORM_XLIB_KHR}
    vkGetPhysicalDeviceXlibPresentationSupportKHR: TvkGetPhysicalDeviceXlibPresentationSupportKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
{$ENDIF VK_USE_PLATFORM_XLIB_KHR}
{$IFDEF VK_USE_PLATFORM_XCB_KHR}
    vkCreateXcbSurfaceKHR: TvkCreateXcbSurfaceKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
{$ENDIF VK_USE_PLATFORM_XCB_KHR}
{$IFDEF VK_USE_PLATFORM_XCB_KHR}
    vkGetPhysicalDeviceXcbPresentationSupportKHR: TvkGetPhysicalDeviceXcbPresentationSupportKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
{$ENDIF VK_USE_PLATFORM_XCB_KHR}
    vkCreateDebugReportCallbackEXT: TvkCreateDebugReportCallbackEXT{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkDestroyDebugReportCallbackEXT: TvkDestroyDebugReportCallbackEXT{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkDebugReportMessageEXT: TvkDebugReportMessageEXT{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkDebugMarkerSetObjectNameEXT: TvkDebugMarkerSetObjectNameEXT{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkDebugMarkerSetObjectTagEXT: TvkDebugMarkerSetObjectTagEXT{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdDebugMarkerBeginEXT: TvkCmdDebugMarkerBeginEXT{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdDebugMarkerEndEXT: TvkCmdDebugMarkerEndEXT{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdDebugMarkerInsertEXT: TvkCmdDebugMarkerInsertEXT{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetPhysicalDeviceExternalImageFormatPropertiesNV: TvkGetPhysicalDeviceExternalImageFormatPropertiesNV{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
{$IFDEF VK_USE_PLATFORM_WIN32_KHR}
    vkGetMemoryWin32HandleNV: TvkGetMemoryWin32HandleNV{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
{$ENDIF VK_USE_PLATFORM_WIN32_KHR}
    vkCmdDrawIndirectCountAMD: TvkCmdDrawIndirectCountAMD{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdDrawIndexedIndirectCountAMD: TvkCmdDrawIndexedIndirectCountAMD{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdProcessCommandsNVX: TvkCmdProcessCommandsNVX{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdReserveSpaceForCommandsNVX: TvkCmdReserveSpaceForCommandsNVX{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCreateIndirectCommandsLayoutNVX: TvkCreateIndirectCommandsLayoutNVX{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkDestroyIndirectCommandsLayoutNVX: TvkDestroyIndirectCommandsLayoutNVX{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCreateObjectTableNVX: TvkCreateObjectTableNVX{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkDestroyObjectTableNVX: TvkDestroyObjectTableNVX{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkRegisterObjectsNVX: TvkRegisterObjectsNVX{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkUnregisterObjectsNVX: TvkUnregisterObjectsNVX{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetPhysicalDeviceGeneratedCommandsPropertiesNVX: TvkGetPhysicalDeviceGeneratedCommandsPropertiesNVX{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetPhysicalDeviceFeatures2KHR: TvkGetPhysicalDeviceFeatures2KHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetPhysicalDeviceProperties2KHR: TvkGetPhysicalDeviceProperties2KHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetPhysicalDeviceFormatProperties2KHR: TvkGetPhysicalDeviceFormatProperties2KHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetPhysicalDeviceImageFormatProperties2KHR: TvkGetPhysicalDeviceImageFormatProperties2KHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetPhysicalDeviceQueueFamilyProperties2KHR: TvkGetPhysicalDeviceQueueFamilyProperties2KHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetPhysicalDeviceMemoryProperties2KHR: TvkGetPhysicalDeviceMemoryProperties2KHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetPhysicalDeviceSparseImageFormatProperties2KHR: TvkGetPhysicalDeviceSparseImageFormatProperties2KHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdPushDescriptorSetKHR: TvkCmdPushDescriptorSetKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkTrimCommandPoolKHR: TvkTrimCommandPoolKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetPhysicalDeviceExternalBufferPropertiesKHX: TvkGetPhysicalDeviceExternalBufferPropertiesKHX{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
{$IFDEF VK_USE_PLATFORM_WIN32_KHX}
    vkGetMemoryWin32HandleKHX: TvkGetMemoryWin32HandleKHX{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
{$ENDIF VK_USE_PLATFORM_WIN32_KHX}
{$IFDEF VK_USE_PLATFORM_WIN32_KHX}
    vkGetMemoryWin32HandlePropertiesKHX: TvkGetMemoryWin32HandlePropertiesKHX{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
{$ENDIF VK_USE_PLATFORM_WIN32_KHX}
    vkGetMemoryFdKHX: TvkGetMemoryFdKHX{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetMemoryFdPropertiesKHX: TvkGetMemoryFdPropertiesKHX{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetPhysicalDeviceExternalSemaphorePropertiesKHX: TvkGetPhysicalDeviceExternalSemaphorePropertiesKHX{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
{$IFDEF VK_USE_PLATFORM_WIN32_KHX}
    vkGetSemaphoreWin32HandleKHX: TvkGetSemaphoreWin32HandleKHX{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
{$ENDIF VK_USE_PLATFORM_WIN32_KHX}
{$IFDEF VK_USE_PLATFORM_WIN32_KHX}
    vkImportSemaphoreWin32HandleKHX: TvkImportSemaphoreWin32HandleKHX{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
{$ENDIF VK_USE_PLATFORM_WIN32_KHX}
    vkGetSemaphoreFdKHX: TvkGetSemaphoreFdKHX{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkImportSemaphoreFdKHX: TvkImportSemaphoreFdKHX{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkReleaseDisplayEXT: TvkReleaseDisplayEXT{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
{$IFDEF VK_USE_PLATFORM_XLIB_XRANDR_EXT}
    vkAcquireXlibDisplayEXT: TvkAcquireXlibDisplayEXT{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
{$ENDIF VK_USE_PLATFORM_XLIB_XRANDR_EXT}
{$IFDEF VK_USE_PLATFORM_XLIB_XRANDR_EXT}
    vkGetRandROutputDisplayEXT: TvkGetRandROutputDisplayEXT{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
{$ENDIF VK_USE_PLATFORM_XLIB_XRANDR_EXT}
    vkDisplayPowerControlEXT: TvkDisplayPowerControlEXT{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkRegisterDeviceEventEXT: TvkRegisterDeviceEventEXT{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkRegisterDisplayEventEXT: TvkRegisterDisplayEventEXT{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetSwapchainCounterEXT: TvkGetSwapchainCounterEXT{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetPhysicalDeviceSurfaceCapabilities2EXT: TvkGetPhysicalDeviceSurfaceCapabilities2EXT{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkEnumeratePhysicalDeviceGroupsKHX: TvkEnumeratePhysicalDeviceGroupsKHX{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetDeviceGroupPeerMemoryFeaturesKHX: TvkGetDeviceGroupPeerMemoryFeaturesKHX{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkBindBufferMemory2KHX: TvkBindBufferMemory2KHX{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkBindImageMemory2KHX: TvkBindImageMemory2KHX{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdSetDeviceMaskKHX: TvkCmdSetDeviceMaskKHX{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetDeviceGroupPresentCapabilitiesKHX: TvkGetDeviceGroupPresentCapabilitiesKHX{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetDeviceGroupSurfacePresentModesKHX: TvkGetDeviceGroupSurfacePresentModesKHX{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkAcquireNextImage2KHX: TvkAcquireNextImage2KHX{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdDispatchBaseKHX: TvkCmdDispatchBaseKHX{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetPhysicalDevicePresentRectanglesKHX: TvkGetPhysicalDevicePresentRectanglesKHX{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCreateDescriptorUpdateTemplateKHR: TvkCreateDescriptorUpdateTemplateKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkDestroyDescriptorUpdateTemplateKHR: TvkDestroyDescriptorUpdateTemplateKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkUpdateDescriptorSetWithTemplateKHR: TvkUpdateDescriptorSetWithTemplateKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdPushDescriptorSetWithTemplateKHR: TvkCmdPushDescriptorSetWithTemplateKHR{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkSetHdrMetadataEXT: TvkSetHdrMetadataEXT{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetRefreshCycleDurationGOOGLE: TvkGetRefreshCycleDurationGOOGLE{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkGetPastPresentationTimingGOOGLE: TvkGetPastPresentationTimingGOOGLE{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
{$IFDEF VK_USE_PLATFORM_IOS_MVK}
    vkCreateIOSSurfaceMVK: TvkCreateIOSSurfaceMVK{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
{$ENDIF VK_USE_PLATFORM_IOS_MVK}
{$IFDEF VK_USE_PLATFORM_MACOS_MVK}
    vkCreateMacOSSurfaceMVK: TvkCreateMacOSSurfaceMVK{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
{$ENDIF VK_USE_PLATFORM_MACOS_MVK}
    vkCmdSetViewportWScalingNV: TvkCmdSetViewportWScalingNV{$IFDEF VULKAN_FLAT} = nil{$ENDIF};
    vkCmdSetDiscardRectangleEXT: TvkCmdSetDiscardRectangleEXT{$IFDEF VULKAN_FLAT} = nil{$ENDIF};

